[supervisord]
nodaemon=true

[program:laravel]
directory=/var/www/html
command=bash -c "php artisan config:cache && php artisan route:cache && php artisan view:cache && apache2-foreground"
autostart=true
autorestart=true
stdout_logfile=/var/log/laravel.out.log
stderr_logfile=/var/log/laravel.err.log

[program:whatsapp-bot]
directory=/var/www/html/whatsapp_bot
command=python3 bot.py
autostart=true
autorestart=true
stdout_logfile=/var/log/bot.out.log
stderr_logfile=/var/log/bot.err.log
