<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit School Information</title>
    <link rel="stylesheet" href="{{ asset('assets/css/assignment.css') }}">
    <style>
        /* Additional styling for edit mode */
        .readonly-field {
            background-color: #f5f5f5;
            cursor: not-allowed;
        }
        .form-section {
            margin-bottom: 2rem;
            padding: 1rem;
            border: 1px solid #ddd;
            border-radius: 5px;
        }
        .form-section h3 {
            margin-top: 0;
            color: #2c3e50;
        }
        /* Subjects table styling */
        .subjects-table {
            width: 100%;
            border-collapse: collapse;
            margin: 1rem 0;
        }
        .subjects-table th, .subjects-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }
        .subjects-table th {
            background-color: #f2f2f2;
        }
        .combination-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 1.5rem;
        }
        .combination-table th, .combination-table td {
            border: 1px solid #ddd;
            padding: 8px;
        }
        .school-type-subjects {
            display: none;
            margin-top: 1.5rem;
        }
        .form-groupp {
            margin-bottom: 2rem;
            padding: 1rem;
            border: 1px solid #ddd;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h2>Update School Information</h2>
            <p class="text-muted" style= 
            'color: #4154f1;'><b>Editing: {{ $school->school_name }} (ID: {{ $school->school_id }})</b></p>
        </header>

        <form action="{{ route('school.update') }}" method="POST">
            @csrf
            @method('PUT')

            <!-- School Basic Information Section -->
            <div class="form-section">
                <h3 style="color: #259925;">School Details</h3>
                
                <div class="form-group">
                    <label for="school-name">School Name:</label>
                    <input type="text" id="school-name" name="school_name" 
                           value="{{ $school->school_name }}" class="readonly-field" readonly>
                </div>

                <div class="form-group">
                    <label for="school-id">School ID:</label>
                    <input type="text" id="school-id" name="school_id" 
                           value="{{ $school->school_id }}" class="readonly-field" readonly>
                </div>

                <div class="form-group">
                    <label for="school-type">School Type:</label>
                    <input type="text" id="school-type" name="school_type" 
                           value="{{ ucfirst($school->school_type) }}" 
                           class="readonly-field" readonly>
                </div>

                <div class="form-group">
                    <label for="region">Region:</label>
                    <input type="text" id="region" name="region" 
                           value="{{ $school->region }}" class="readonly-field" readonly>
                </div>

                <div class="form-group">
                    <label for="district">District:</label>
                    <input type="text" id="district" name="district" 
                           value="{{ $school->district }}" class="readonly-field" readonly>
                </div>
            </div>

          <!-- Subjects Selection Section -->
<div class="form-groupp">
    <h3>Subjects Offered</h3>
    <div id="subjects-container">
        <!-- Primary School Subjects -->
        <div id="primary-subjects" class="school-type-subjects" style="display:none;">
            <h2>Primary School Subjects</h2>
            <table>
                <thead>
                    <tr>
                        <th>Standard</th>
                        <th>English</th>
                        <th>Mathematics</th>
                        <th>Science</th>
                        <th>Civics</th>
                        <th>Kiswahili</th>
                        <th>History</th>
                        <th>Geography</th>
                        <th>S/work</th>
                        <th>M/jamii</th>
                    </tr>
                </thead>
                <tbody id="primary-subjects-body">
                    <!-- Rows will be generated by JavaScript -->
                </tbody>
            </table>
        </div>

        <!-- Secondary School Subjects -->
        <div id="secondary-subjects" class="school-type-subjects" style="display:none;">
            <h2>Secondary School Subjects (Forms 1-2)</h2>
            <table>
                <thead>
                    <tr>
                        <th>Form</th>
                        <th>Physics</th>
                        <th>Chemistry</th>
                        <th>Biology</th>
                        <th>Geography</th>
                        <th>History</th>
                        <th>Mathematics</th>
                        <th>English</th>
                        <th>Kiswahili</th>
                        <th>Civics</th>
                    </tr>
                </thead>
                <tbody id="secondary-subjects-body">
                    <!-- Rows will be generated by JavaScript -->
                </tbody>
            </table>
        </div>

        <!-- Advanced Level Subjects -->
        <div id="advance-subjects" class="school-type-subjects" style="display:none;">
            <h2>Advanced Level Combinations</h2>

            <!-- Science Combinations -->
            <h3>Science Combinations</h3>
            <table class="combination-table">
                <thead class="combination-heading">
                    <tr>
                        <th>Select</th>
                        <th>Combination Code</th>
                        <th>Subjects</th>
                    </tr>
                </thead>
                <tbody id="science-combinations">
                    <!-- Science combinations will be generated here -->
                </tbody>
            </table>

            <!-- Arts Combinations -->
            <h3>Arts Combinations</h3>
            <table class="combination-table">
                <thead class="combination-heading">
                    <tr>
                        <th>Select</th>
                        <th>Combination Code</th>
                        <th>Subjects</th>
                    </tr>
                </thead>
                <tbody id="arts-combinations">
                    <!-- Arts combinations will be generated here -->
                </tbody>
            </table>

            <!-- Business Combinations -->
            <h3>Business Combinations</h3>
            <table class="combination-table">
                <thead class="combination-heading">
                    <tr>
                        <th>Select</th>
                        <th>Combination Code</th>
                        <th>Subjects</th>
                    </tr>
                </thead>
                <tbody id="business-combinations">
                    <!-- Business combinations will be generated here -->
                </tbody>
            </table>

            <!-- Technical Combinations -->
            <h3>Technical Combinations</h3>
            <table class="combination-table">
                <thead class="combination-heading">
                    <tr>
                        <th>Select</th>
                        <th>Combination Code</th>
                        <th>Subjects</th>
                    </tr>
                </thead>
                <tbody id="technical-combinations">
                    <!-- Technical combinations will be generated here -->
                </tbody>
            </table>
        </div>
    </div>
</div>


            <!-- Fees Structure Section -->
            <div class="formm-section">
                <h3>Fee Structure</h3>
                <div class="table-responsive">
                    <table class="fee-table">
                        <thead>
                            <tr>
                                <th>Class/Form</th>
                                <th>Tuition Fee</th>
                                <th>Other Fees</th>
                                <th>Total Fees</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($school->fees_structure as $class => $fees)
                            <tr>
                                <td>{{ $class }}</td>
                                <td>
                                    <input type="number" name="fees[{{ $class }}][tuition]" 
                                           value="{{ $fees['tuition'] ?? 0 }}" required>
                                </td>
                                <td>
                                    <input type="number" name="fees[{{ $class }}][other]" 
                                           value="{{ $fees['other'] ?? 0 }}" required>
                                </td>
                                <td class="total-fee">{{ ($fees['tuition'] ?? 0) + ($fees['other'] ?? 0) }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
           
            <!-- Grading System Section -->
            <div class="formm-section">
                <h3>Grading System</h3>
                <table class="grading-table">
                    <thead>
                        <tr>
                            <th>Grade</th>
                            <th>Minimum Score</th>
                            <th>Maximum Score</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($school->grades as $grade => $range)
                        <tr>
                            <td>{{ $grade }}</td>
                            <td>
                                <input type="number" name="grades[{{ $grade }}][from]" 
                                       value="{{ $range['from'] }}" required>
                            </td>
                            <td>
                                <input type="number" name="grades[{{ $grade }}][to]" 
                                       value="{{ $range['to'] }}" required>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            <div class="form-actions">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i> Update School Data
                </button>
                <a href="{{ url()->previous() }}" class="btn btn-secondary">
                    Cancel
                </a>
            </div>
        </form>
    </div>

    
    <script>
    // Auto-calculate fee totals
    document.querySelectorAll('.fee-table input[type="number"]').forEach(input => {
        input.addEventListener('input', function () {
            const row = this.closest('tr');
            const tuition = parseFloat(row.querySelector('input[name$="[tuition]"]').value) || 0;
            const other = parseFloat(row.querySelector('input[name$="[other]"]').value) || 0;
            row.querySelector('.total-fee').textContent = tuition + other;
        });
    });

    document.addEventListener('DOMContentLoaded', function () {
        const schoolType = "{{ $school->school_type }}";
const subjectsData = {!! json_encode($school->subjects ?: []) !!};
        showRelevantSubjectsSection(schoolType);
        loadSubjects(schoolType, subjectsData);
    });

    function showRelevantSubjectsSection(type) {
        document.querySelectorAll('.school-type-subjects').forEach(section => {
            section.style.display = 'none';
        });

        if (type === 'primary') {
            document.getElementById('primary-subjects').style.display = 'block';
        } else if (type === 'secondary') {
            document.getElementById('secondary-subjects').style.display = 'block';
        } else if (type === 'advance') {
            document.getElementById('advance-subjects').style.display = 'block';
        }
    }

    function isSubjectChecked(data, grade, subject) {
        if (!data) return false;
        return data[grade] && data[grade][subject];
    }

    function loadSubjects(type, data) {
        switch (type) {
            case 'primary':
                loadPrimarySubjects(data);
                break;
            case 'secondary':
                loadSecondarySubjects(data);
                break;
            case 'advance':
                loadAdvancedSubjects(data);
                break;
            default:
                console.error('Unknown school type:', type);
        }
    }

    function loadPrimarySubjects(data) {
        const tbody = document.getElementById('primary-subjects-body');
        tbody.innerHTML = ''; // Clear existing rows

        const subjects = ['english', 'mathematics', 'science', 'civics', 'kiswahili', 'history', 'geography', 'skazi', 'maarifa'];

        for (let std = 1; std <= 7; std++) {
            const row = document.createElement('tr');
            row.innerHTML = `
                <td>Standard ${std}</td>
                ${subjects.map(sub => `
                    <td><input type="checkbox" name="subjects[Standard ${std}][${sub}]" ${isSubjectChecked(data, `Standard ${std}`, sub) ? 'checked' : ''}></td>
                `).join('')}
            `;
            tbody.appendChild(row);
        }
    }

    function loadSecondarySubjects(data) {
        const tbody = document.getElementById('secondary-subjects-body');
        tbody.innerHTML = ''; // Clear existing rows

        const subjects = ['physics', 'chemistry', 'biology', 'geography', 'history', 'mathematics', 'english', 'kiswahili', 'civics'];

        for (let form = 1; form <= 2; form++) {
            const row = document.createElement('tr');
            row.innerHTML = `
                <td>Form ${form}</td>
                ${subjects.map(sub => {
                    const autoCheck = ['physics', 'chemistry', 'biology'].includes(sub) && form >= 2;
                    return `
                        <td><input type="checkbox" name="subjects[Form ${form}][${sub}]" ${isSubjectChecked(data, `Form ${form}`, sub) || autoCheck ? 'checked' : ''}></td>
                    `;
                }).join('')}
            `;
            tbody.appendChild(row);
        }
    }

    function loadAdvancedSubjects(data) {
        const categories = {
            Science: [
                { code: 'PCM', name: 'Physics, Chemistry, Mathematics' },
                { code: 'PCB', name: 'Physics, Chemistry, Biology' },
                { code: 'PGM', name: 'Physics, Geography, Mathematics' },
                { code: 'PMCs', name: 'Physics, Mathematics, Computer Science' }
            ],
            Arts: [
                { code: 'HGE', name: 'History, Geography, Economics' },
                { code: 'HKL', name: 'History, Kiswahili, English' },
                { code: 'HGAr', name: 'History, Geography, Arabic' },
                { code: 'HGL', name: 'History, Geography, English' }
            ],
            Business: [
                { code: 'EBuAc', name: 'Economics, Business Studies, Accountancy' },
                { code: 'ECAc', name: 'Economics, Commerce, Accountancy' },
                { code: 'EGM', name: 'Economics, Geography, Mathematics' }
            ],
            Technical: [
                { code: 'BNS', name: 'Biology, Nutrition, Sports' },
                { code: 'KLF', name: 'Kiswahili, English, French' },
                { code: 'KArCh', name: 'Kiswahili, Arabic, Chinese' }
            ]
        };

        for (const category in categories) {
            const tbody = document.getElementById(`${category.toLowerCase()}-combinations`);
            if (!tbody) continue;
            tbody.innerHTML = ''; // clear existing rows
            categories[category].forEach(combo => {
                const isChecked = data?.[category]?.some(c => c.code === combo.code) ? 'checked' : '';
                const row = document.createElement('tr');
                row.innerHTML = `
                    <td><input type="checkbox" name="combinations[${category}][]" value="${combo.code}" ${isChecked}></td>
                    <td>${combo.code}</td>
                    <td>${combo.name}</td>
                `;
                tbody.appendChild(row);
            });
        }
    }
</script>

</body>
</html>