<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration Form</title>
    <link rel="stylesheet" href="{{ asset('assets/css/assignment.css') }}">
</head>

<body>
    <div class="container">
        <header>
            <h2>Registration Form</h2>
        </header>

        <form action="{{ route('schools.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <input type="hidden" name="_token" value="{{ csrf_token() }}">

            <div class="form-group">
                <label for="school-name">School Name:</label>
                <input type="text" id="school-name" name="school_name" placeholder="Enter school name" required>
            </div>

            <div class="form-group">
                <label for="school-id">School ID:</label>
                <input type="number" id="school-id" name="school_id" placeholder="Enter school id" required>
            </div>

            <div class="form-group">
                <label for="school-type">School Type:</label>
                <select id="school-type" name="school_type" required>
                    <option value="primary">Primary</option>
                    <option value="secondary">Secondary</option>
                    <option value="advance">Advanced</option>
                </select>
            </div>

            <div class="form-group">
                <label for="region">Region:</label>
                <select id="region" name="region" required>
                    <option value="">Select Region</option>
                    <option value="Arusha">Arusha</option>
                    <option value="Dar es Salaam">Dar es Salaam</option>
                    <option value="Dodoma">Dodoma</option>
                    <option value="Mbeya">Mbeya</option>
                    <option value="Mwanza">Mwanza</option>
                </select>
            </div>

            <div class="form-group">
                <label for="district">District:</label>
                <select id="district" name="district" required>
                    <option value="">Select District</option>
                </select>
            </div>

            <!-- Class Fees Table -->
            <div id="fees-table" class="fees-table-container">
                <h2>Class Fees Structure</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Class</th>
                            <th>Tuition Fee</th>
                            <th>Other Fees</th>
                            <th>Total Fee</th>
                        </tr>
                    </thead>
                    <tbody id="fees-tbody">
                        <!-- Rows will be generated by JavaScript -->
                    </tbody>
                </table>
            </div>

            <!-- Subjects Selection Section -->
            <div class="form-groupp">
                <div id="primary-subjects" class="school-type-subjects" style="display:none;">
                    <h2>Primary School Subjects</h2>
                    <table>
                        <thead>
                            <tr>
                                <th>Standard</th>
                                <th>English</th>
                                <th>Mathematics</th>
                                <th>Science</th>
                                <th>Civics</th>
                                <th>Kiswahili</th>
                                <th>History</th>
                                <th>Geography</th>
                                <th>S/work</th>
                                <th>M/jamii</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Rows will be generated by JavaScript -->
                        </tbody>
                    </table>
                </div>

                <div id="secondary-subjects" class="school-type-subjects" style="display:none;">
                    <h2>Secondary School Subjects (Forms 1-2)</h2>
                    <table>
                        <thead>
                            <tr>
                                <th>Form</th>
                                <th>Physics</th>
                                <th>Chemistry</th>
                                <th>Biology</th>
                                <th>Geography</th>
                                <th>History</th>
                                <th>Mathematics</th>
                                <th>English</th>
                                <th>Kiswahili</th>
                                <th>Civics</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Rows will be generated by JavaScript -->
                        </tbody>
                    </table>
                </div>

                <div id="advance-subjects" class="school-type-subjects" style="display:none;">
                    <h2>Advanced Level Combinations</h2> <!-- Hii inabaki h2 kama ulivyo weka -->

                    <!-- SCIENCE COMBINATIONS -->
                    <h3>Science Combinations</h3> <!-- Moved outside table -->
                    <table class="combination-table">
                        <thead class="combination-heading">
                            <tr>
                                <th>Select</th>
                                <th>Combination Code</th>
                                <th>Subjects</th>
                            </tr>
                        </thead>
                        <tbody id="science-combinations">
                            <!-- Science combinations will be generated here -->
                        </tbody>
                    </table>

                    <!-- ARTS COMBINATIONS -->
                    <h3>Arts Combinations</h3> <!-- Moved outside table -->
                    <table class="combination-table">
                        <thead class="combination-heading">
                            <tr>
                                <th>Select</th>
                                <th>Combination Code</th>
                                <th>Subjects</th>
                            </tr>
                        </thead>
                        <tbody id="arts-combinations">
                            <!-- Arts combinations will be generated here -->
                        </tbody>
                    </table>

                    <!-- BUSINESS COMBINATIONS -->
                    <h3>Business Combinations</h3> <!-- Moved outside table -->
                    <table class="combination-table">
                        <thead class="combination-heading">
                            <tr>
                                <th>Select</th>
                                <th>Combination Code</th>
                                <th>Subjects</th>
                            </tr>
                        </thead>
                        <tbody id="business-combinations">
                            <!-- Business combinations will be generated here -->
                        </tbody>
                    </table>

                    <!-- TECHNICAL COMBINATIONS -->
                    <h3>Technical Combinations</h3> <!-- Moved outside table -->
                    <table class="combination-table">
                        <thead class="combination-heading">
                            <tr>
                                <th>Select</th>
                                <th>Combination Code</th>
                                <th>Subjects</th>
                            </tr>
                        </thead>
                        <tbody id="technical-combinations">
                            <!-- Technical combinations will be generated here -->
                        </tbody>
                    </table>
                </div>

            </div>

            <!-- Grading System Table -->
            <div id="grading-table" class="grading-table-container">
                <h2>Grading System Table</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Grade</th>
                            <th>From</th>
                            <th>Up To</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>A</td>
                            <td><input type="number" name="grade_A_from" value="75" required></td>
                            <td><input type="number" name="grade_A_to" value="100" required></td>
                        </tr>
                        <tr>
                            <td>B</td>
                            <td><input type="number" name="grade_B_from" value="65" required></td>
                            <td><input type="number" name="grade_B_to" value="74" required></td>
                        </tr>
                        <tr>
                            <td>C</td>
                            <td><input type="number" name="grade_C_from" value="45" required></td>
                            <td><input type="number" name="grade_C_to" value="64" required></td>
                        </tr>
                        <tr>
                            <td>D</td>
                            <td><input type="number" name="grade_D_from" value="30" required></td>
                            <td><input type="number" name="grade_D_to" value="44" required></td>
                        </tr>
                        <tr>
                            <td>F</td>
                            <td><input type="number" name="grade_F_from" value="0" required></td>
                            <td><input type="number" name="grade_F_to" value="29" required></td>
                        </tr>
                        <tr class="special-grade" style="display: none;">
                            <td>E</td>
                            <td><input type="number" name="grade_E_from" value="40" required></td>
                            <td><input type="number" name="grade_E_to" value="49" required></td>
                        </tr>
                        <tr class="special-grade" style="display: none;">
                            <td>S</td>
                            <td><input type="number" name="grade_S_from" value="35" required></td>
                            <td><input type="number" name="grade_S_to" value="39" required></td>
                        </tr>
                        <tr class="special-grade" style="display: none;">
                            <td>F</td>
                            <td><input type="number" name="grade_F_from_advance" value="0" required></td>
                            <td><input type="number" name="grade_F_to_advance" value="34" required></td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <button type="submit" class="btn-primary">Register</button>
        </form>
    </div>

    <script>
        // Handle region change to update districts dynamically
        const regions = {
            "Arusha": ["Arusha", "Arumeru", "Ngorongoro", "Longido", "Monduli", "Karatu"],
            "Dar es Salaam": ["Kinondono", "Ilala", "Temeke", "Kigamboni", "Ubungo"],
            "Dodoma": ["Chamwino", "Dodoma", "Chemba", "Kondoa"],
            "Mbeya": ["Chunya", "Kyela", "Mbeya", "Rungwe", "Mbarali"],
            "Mwanza": ["Ilemela", "Nyamagana", "Kwimba", "Sengerema", "Ukerewe", "Magu", "Misungwi"]
        };

        document.getElementById('region').addEventListener('change', function () {
            const region = this.value;
            const districtSelect = document.getElementById('district');
            districtSelect.innerHTML = '<option value="">Select District</option>';

            if (region && regions[region]) {
                regions[region].forEach(function (district) {
                    const option = document.createElement('option');
                    option.value = district;
                    option.textContent = district;
                    districtSelect.appendChild(option);
                });
            }
        });

        // Initially load districts for the first region
        document.getElementById('region').dispatchEvent(new Event('change'));

        // Handle School Type Change for Subjects and Fees
        const schoolTypeSelect = document.getElementById('school-type');
        const subjectSections = document.querySelectorAll('.school-type-subjects');
        const gradingTable = document.getElementById('grading-table');
        const specialGrades = document.querySelectorAll('.special-grade');
        const feesTbody = document.getElementById('fees-tbody');

        schoolTypeSelect.addEventListener('change', function () {
            // Hide all subject sections first
            subjectSections.forEach(section => {
                section.style.display = 'none';
            });

            // Show the appropriate subject section
            const selectedType = this.value;
            if (selectedType === 'primary') {
                document.getElementById('primary-subjects').style.display = 'block';
                generatePrimarySubjectsTable();
                generatePrimaryFeesTable();
            } else if (selectedType === 'secondary') {
                document.getElementById('secondary-subjects').style.display = 'block';
                generateSecondarySubjectsTable();
                generateSecondaryFeesTable();
            } else if (selectedType === 'advance') {
                document.getElementById('advance-subjects').style.display = 'block';
                generateAdvanceCombinationsTable();
                generateAdvanceFeesTable();
            }

            // Handle grading system changes
            if (selectedType === 'advance') {
                specialGrades.forEach(grade => grade.style.display = 'table-row');
                document.querySelector('tr:nth-child(5)').style.display = 'none';
            } else {
                specialGrades.forEach(grade => grade.style.display = 'none');
                document.querySelector('tr:nth-child(5)').style.display = 'table-row';
            }
        });

        // Generate Primary School Subjects Table
        function generatePrimarySubjectsTable() {
            const tbody = document.querySelector('#primary-subjects tbody');
            tbody.innerHTML = '';

            for (let std = 1; std <= 7; std++) {
                const row = document.createElement('tr');
                row.innerHTML = `
                <td>Standard ${std}</td>
                <td><input type="checkbox" name="primary_std${std}_english" checked></td>
                <td><input type="checkbox" name="primary_std${std}_mathematics" checked></td>
                <td><input type="checkbox" name="primary_std${std}_science" checked></td>
                <td><input type="checkbox" name="primary_std${std}_civics" checked></td>
                <td><input type="checkbox" name="primary_std${std}_kiswahili" checked></td>
                <td><input type="checkbox" name="primary_std${std}_History" checked></td>
                <td><input type="checkbox" name="primary_std${std}_Geography" checked></td>
                <td><input type="checkbox" name="primary_std${std}_skazi" checked></td>
                <td><input type="checkbox" name="primary_std${std}_Maarifa" checked></td>
            `;
                tbody.appendChild(row);
            }
        }

        // Generate Secondary School Subjects Table (Forms 1-2 only)
        function generateSecondarySubjectsTable() {
            const tbody = document.querySelector('#secondary-subjects tbody');
            tbody.innerHTML = '';

            for (let form = 1; form <= 2; form++) {
                const row = document.createElement('tr');
                row.innerHTML = `
                <td>Form ${form}</td>
                <td><input type="checkbox" name="secondary_form${form}_physics" ${form >= 2 ? 'checked' : ''}></td>
                <td><input type="checkbox" name="secondary_form${form}_chemistry" ${form >= 2 ? 'checked' : ''}></td>
                <td><input type="checkbox" name="secondary_form${form}_biology" ${form >= 2 ? 'checked' : ''}></td>
                <td><input type="checkbox" name="secondary_form${form}_geography" checked></td>
                <td><input type="checkbox" name="secondary_form${form}_history" checked></td>
                <td><input type="checkbox" name="secondary_form${form}_mathematics" checked></td>
                <td><input type="checkbox" name="secondary_form${form}_english" checked></td>
                <td><input type="checkbox" name="secondary_form${form}_kiswahili" checked></td>
                <td><input type="checkbox" name="secondary_form${form}_civics" checked></td>
            `;
                tbody.appendChild(row);
            }
        }

        // Generate Advanced Level Combinations Table
        function generateAdvanceCombinationsTable() {
            // Define all combinations by category
            const combinations = {
                science: [
                    { code: 'PCM', name: 'Physics, Chemistry, Mathematics' },
                    { code: 'PCB', name: 'Physics, Chemistry, Biology' },
                    { code: 'PGM', name: 'Physics, Geography, Mathematics' },
                    { code: 'PMCs', name: 'Physics, Mathematics, Computer Science' }
                ],
                arts: [
                    { code: 'HGE', name: 'History, Geography, Economics' },
                    { code: 'HKL', name: 'History, Kiswahili, English' },
                    { code: 'HGAr', name: 'History, Geography, Arabic' },
                    { code: 'HGL', name: 'History, Geography, English' }
                ],
                business: [
                    { code: 'EBuAc', name: 'Economics, Business Studies, Accountancy' },
                    { code: 'ECAc', name: 'Economics, Commerce, Accountancy' },
                    { code: 'EGM', name: 'Economics, Geography, Mathematics' }
                ],
                technical: [
                    { code: 'BNS', name: 'Biology, Nutrition, Sports' },
                    { code: 'KLF', name: 'Kiswahili, English, French' },
                    { code: 'KArCh', name: 'Kiswahili, Arabic, Chinese' }
                ]
            };

            // Generate rows for each category
            for (const [category, comboList] of Object.entries(combinations)) {
                const tbody = document.getElementById(`${category}-combinations`);
                tbody.innerHTML = '';

                comboList.forEach(combo => {
                    const row = document.createElement('tr');
                    row.className = 'combination-row';
                    row.innerHTML = `
                    <td><input type="checkbox" name="combinations[]" value="${combo.code}"></td>
                    <td>${combo.code}</td>
                    <td>${combo.name}</td>
                `;
                    tbody.appendChild(row);
                });
            }
        }

        // Generate Primary School Fees Table
function generatePrimaryFeesTable() {
    feesTbody.innerHTML = '';

    for (let std = 1; std <= 7; std++) {
        const row = document.createElement('tr');
        row.innerHTML = `
            <td>Standard ${std}</td>
            <td><input type="number" name="tuition_fee_std${std}" placeholder="Tuition fee" required></td>
            <td><input type="number" name="other_fee_std${std}" placeholder="Other fees" required></td>
            <td>
                <span id="total_fee_std${std}">0</span>
                <input type="hidden" name="total_fee_std${std}" id="hidden_total_fee_std${std}" value="0">
            </td>
        `;
        feesTbody.appendChild(row);
    }
}

// Generate Secondary School Fees Table (Forms 1-4)
function generateSecondaryFeesTable() {
    feesTbody.innerHTML = '';

    for (let form = 1; form <= 4; form++) {
        const row = document.createElement('tr');
        row.innerHTML = `
            <td>Form ${form}</td>
            <td><input type="number" name="tuition_fee_form${form}" placeholder="Tuition fee" required></td>
            <td><input type="number" name="other_fee_form${form}" placeholder="Other fees" required></td>
            <td>
                <span id="total_fee_form${form}">0</span>
                <input type="hidden" name="total_fee_form${form}" id="hidden_total_fee_form${form}" value="0">
            </td>
        `;
        feesTbody.appendChild(row);
    }
}

// Generate Advanced Level Fees Table (Forms 5-6)
function generateAdvanceFeesTable() {
    feesTbody.innerHTML = '';

    for (let form = 5; form <= 6; form++) {
        const row = document.createElement('tr');
        row.innerHTML = `
            <td>Form ${form}</td>
            <td><input type="number" name="tuition_fee_form${form}" placeholder="Tuition fee" required></td>
            <td><input type="number" name="other_fee_form${form}" placeholder="Other fees" required></td>
            <td>
                <span id="total_fee_form${form}">0</span>
                <input type="hidden" name="total_fee_form${form}" id="hidden_total_fee_form${form}" value="0">
            </td>
        `;
        feesTbody.appendChild(row);
    }
}


      document.addEventListener('input', function (e) {
    if (e.target.name.includes('tuition_fee_') || e.target.name.includes('other_fee_')) {
        const baseName = e.target.name.split('_').slice(2).join('_');

        const tuition = parseFloat(document.querySelector(`input[name="tuition_fee_${baseName}"]`).value) || 0;
        const other = parseFloat(document.querySelector(`input[name="other_fee_${baseName}"]`).value) || 0;

        const total = tuition + other;

        // Update visible text
        const totalSpan = document.getElementById(`total_fee_${baseName}`);
        if (totalSpan) {
            totalSpan.textContent = total.toLocaleString(); // With commas
        }

        // Update hidden input
        const hiddenInput = document.getElementById(`hidden_total_fee_${baseName}`);
        if (hiddenInput) {
            hiddenInput.value = total;
        }
    }
});




        // Initialize the form with default school type
        schoolTypeSelect.dispatchEvent(new Event('change'));


        document.querySelector('form').addEventListener('submit', function(e) {
    // Recalculate all totals before submission as a safety net
    document.querySelectorAll('[name^="tuition_fee_"]').forEach(input => {
        const baseName = input.name.split('_').slice(2).join('_');
        const tuition = parseFloat(input.value) || 0;
        const other = parseFloat(document.querySelector(`input[name="other_fee_${baseName}"]`).value) || 0;
        const totalInput = document.querySelector(`input[name="total_fee_${baseName}"]`);
        
        if (totalInput) {
            totalInput.value = tuition + other;
        }
    });
});
    </script>
</body>

</html>